#     ___    __                _ __  __       
#    /   |  / /___ ___________(_) /_/ /___  __
#   / /| | / / __ `/ ___/ ___/ / __/ __/ / / /
#  / ___ |/ / /_/ / /__/ /  / / /_/ /_/ /_/ / 
# /_/  |_/_/\__,_/\___/_/  /_/\__/\__/\__, /  
#                                    /____/   

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.bright]
black = "0x121212"
blue = "0x6264fe"
cyan = "0x53f7f9"
green = "0xa9df11"
magenta = "0xff4de7"
red = "0xfe0219"
white = "0xfedd83"
yellow = "0xf4df23"

[colors.normal]
black = "0x000000"
blue = "0x6b65da"
cyan = "0x43e7e9"
green = "0x99cf01"
magenta = "0xaf38db"
red = "0xee0009"
white = "0xeecd73"
yellow = "0xe4cf13"

[colors.primary]
background = "0x0d0000"
foreground = "0xefefef"

[font]
size = 14

[font.bold]
family = "SpaceMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SpaceMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Italic"

[font.normal]
family = "SpaceMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = -2

[mouse]
hide_when_typing = true
[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[window]
decorations = "none"
opacity = 0.5
decorations_theme_variant = "Dark"
dynamic_padding = true

[cursor]
blink_interval = 500
[cursor.style]
shape = "Beam"
blinking = "Always"
[cursor.vi_mode_style]
shape = "Beam"
blinking = "Always"

[window.padding]
x = 8
y = 8

