alias poses="sudo chown babkock:babkock "
mkcd() {
	mkdir "$1"
	cd "$1"
}
alias ..="cd .."
alias c="cd "
alias f="feh "
alias u="cd ~/Music"
alias o="cd ~/Documents"
alias d="cd ~/Downloads"
alias p="cd ~/Pictures"
alias t="cd ~/Torrents"
alias i="cd ~/Videos"
alias n="ncmpcpp"
alias g="git"
alias v="vim "
alias ls="ls -hNF --color=auto --group-directories-first"
alias l="ls -hNF --color=auto --group-directories-first"
alias s="ssh tababcock@tannerbabcock.com -p 2222"
alias tre="transmission-remote"
alias trc="transmission-remote-cli"
alias m="mpv "
alias r="ranger"

