alias g="git"
alias v="vim "
alias ls="ls -hNF --color=auto --group-directories-first"
alias l="ls -hNF --color=auto --group-directories-first"
alias s="ssh babkock@192.168.0.3"
alias kt="sudo killall transmission-daemon; transmission-daemon; transmission-remote --no-dht --no-lpd"
alias tre="transmission-remote"
alias t="transmission-remote-cli"
alias m="vlc "
alias r="ranger"

