.TH halp 1 "November 1, 2019" "Key Bindings" "Key Shortcuts"
.SH NAME
halp \- list of my user-defined key shortcuts for several programs
.SH PROGRAMS
\fIMod + Return\fR
--   Terminal (st)

\fIMod + Shift + Return\fR
--   Tabbed Terminal (st)

\fIMod + Space\fR
--   Dmenu

\fIMod + Period\fR (.)
--   Surf

\fIMod + Shift + Period\fR (.)
--   Thunderbird

\fIMod + Comma\fR (,)
--   Ncmpcpp Music Player

\fIMod + Shift + Comma\fR (,)
--   Album Art Display (bum)

\fIMod + Hyphen\fR (-)
--   Transmission

\fIMod + Semicolon\fR (;)
--   Ranger File Browser (urxvt)

\fIMod + Slash\fR (/)
--   Ranger File Browser (st)

\fIMod + Backslash\fR (\\)
--   Filezilla

\fIMod + N\fR
--   Pulse Audio Control

\fIMod + E\fR
--   JGMenu App Launcher

\fIMod + Shift + Slash\fR (/)
--   This Man Page Window

.SH SURF COMMANDS
\fICtrl + Shift + Enter\fR
--   Open new tab

\fICtrl + H\fR
--   Back

\fICtrl + L\fR
--   Forward

\fICtrl + R\fR
--   Refresh

\fICtrl + G\fR
--   Go to address

\fICtrl + F\fR
--   Find string on web page

\fICtrl + N\fR
--   Go to next search result

\fICtrl + Shift + O\fR
--   Open web inspector

\fICtrl + B\fR
--   Add current page to bookmarks

\fICtrl + Shift + K\fR
--   Zoom in

\fICtrl + Shift + J\fR
--   Zoom out

\fICtrl + Shift + W\fR
--   Move tab left

\fICtrl + Shift + E\fR
--   Move tab right

\fICtrl + W\fR
--   Play media on page in MPV

.SS SURF ADDRESS BAR PATTERNS

" \fI[query]\fR"
--   (Note the space) Search Duck Duck Go

"\fBg \fR\fI[query]\fR"
--   Search on Google

"\fBgh \fR\fI[query]\fR"
--   Search on GitHub

"\fBw \fR\fI[query]\fR"
--   Search on Wikipedia

"\fBy \fR\fI[query]\fR"
--   Search on YouTube

"\fBv \fR\fI[query]\fR"
--   Search on Void Linux wiki

.SH SHELL ALIASES

"\fBa \fR\fI[file]\fR"
--   'bat', Rust file viewer and concatenator

"\fBb\fR"
--   'neofetch', system information tool, with options

"\fBc \fR\fI[directory]\fR"
--   cds into the specified directory

"\fBcat \fR\fI[file]\fR"
--   'bat' in place of 'cat'

"\fBconf \fR\fI[program]\fR"
--   Edits the main configuration file for a certain program

"\fBd\fR"
--   cds into ~/Downloads

"\fBdf\fR"
--   'df -h -T' in place of 'df'

"\fBe\fR"
--   'cargo build --release' - compiles Rust project

"\fBf \fR\fI[image]\fR"
--   Opens the image in Feh, image viewer

"\fBg \fR\fI[command] [options]\fR"
--   'git' with no arguments - add 'push', 'pull', etc.

"\fBga \fR\fI[file]\fR"
--   'git add' - adds a file to staging area

"\fBgc \fR\fI[commit or branch] -- [file]\fR"
--   'git checkout' - checks out branch, commit, or file

"\fBgcb \fR\fI[new branch name]\fR"
--   Creates a new branch with name, switches to it

"\fBgcm \fR\fI[commit message]\fR"
--   Commits with the specified message

"\fBgl\fR"
--   'git log' - show last several commits in a pager

"\fBgpush\fR"
--   'git push origin master' - don't run if pushing to another branch

"\fBgpull\fR"
--   'git pull origin master'

"\fBgr \fR\fI[file]\fR"
--   'git remove' - removes file from staging area and deletes it

"\fBgrc \fR\fI[file]\fR"
--   'git remote --cached' - removes from staging area without deleting

"\fBgs\fR"
--   'git status' - show staged and unstaged changes

"\fBi\fR"
--   cds into ~/Videos

"\fBjcommit\fR"
--   Commits with the date for a message, and pushes

"\fBk\fR"
--   'make', optionally with arguments

"\fBkc\fR"
--   'make clean'

"\fBl \fR\fI[directory]\fR"
--   'lsd', Rust file lister, with options

"\fBls \fR\fI[directory]\fR"
--   'lsd' in place of 'ls'

"\fBlsl\fR"
--   'lsd -l', for long listing

"\fBlsa\fR"
--   'lsd -A', for almost all entries

"\fBlsla\fR"
--   'lsd -lA', for long listing of all entries

"\fBlst\fR"
--   'lsd --tree', for tree listing

"\fBm \fR\fI[video file]\fR"
--   Play specified video file in MPV

"\fBn\fR"
--   Opens ncmpcpp Music Player

"\fBo\fR"
--   cds into ~/Documents

"\fBp\fR"
--   cds into ~/Pictures

"\fBr\fR"
--   'ranger', command-line file browser

"\fBs\fR"
--   SSHs into my website

"\fBsc \fR\fI[image]\fR"
--   Take screenshot with 'scrot'

"\fBspi\fR"
--   SSHs into the Raspberry Pi

"\fBt \fR\fI[torrent file]\fR"
--   Start Transmission with specified file

"\fBtr \fR\fI[arguments]\fR"
--   'transmission-remote', with mandatory arguments

"\fBu\fR"
--   cds into ~/Music

"\fBv \fR\fI[file]\fR"
--   Opens the specified file in Vim

"\fBx\fR"
--   Starts a new zsh instance as root

"\fBxk\fR"
--   Show codes for a given key binding

"\fBxp\fR"
--   Get properties of a window

"\fBz \fR\fI[arguments]\fR"
--   'tmux', optionally with arguments

.SH VIM COMMANDS
\fIu\fR
   - Undo

\fICtrl + R\fR
   - Redo

\fICtrl + W\fR
   - Jump to other window

\fIdd\fR
   - Delete the entire current line

\fId$\fR
   - Delete the rest of the current line

\fIdG\fR
   - Deletes entire file

\fIc\fR
   - Cut text in Visual mode

\fIy\fR
   - Copy text in Visual mode

\fIp\fR
   - Paste text in Normal mode

\fI:w\fR
   - Write buffer to file, or with argument to write new file

\fI:q\fR
   - Quit after saving

\fI:q!\fR
   - Quit without saving

\fI:wq\fR
   - Save and quit

\fIG\fR
   - Jump to the bottom of the file

\fIgg\fR
   - Jump to the top of the file

\fI?\fR
   - Backwards search

\fI/\fR
   - Forwards search

.SH BSPWM SHORTCUTS
\fIMod + Shift + E\fR
--   Exit BSPWM

\fIMod + Shift + R\fR
--   Restart BSPWM

\fIMod + Shift + C\fR
--   Close Window

\fIMod + T\fR
--   Tiled Window State

\fIMod + S\fR
--   Floating Window State

\fIMod + F\fR
--   Fullscreen Window State

\fIMod + Shift + Q\fR
--   Switch to Adjacent Window

\fIMod + O\fR
--   Switch to Newer Window

\fIMod + I\fR
--   Switch to Older Window

\fIMod + M\fR
--   Monocle Layout

\fIMod + Arrow Keys\fR
--   Move Floating Window
