.TH halp 1 "August 31, 2019" "BSPWM Key Bindings" "My Key Shortcuts"
.SH NAME
halp \- list of my user-defined key shortcuts
.SH PROGRAMS
Mod + Return
--   Terminal (st)

Mod + Space
--   Dmenu

Mod + Period (.)
--   Surf

Mod + Shift + Period (.)
--   Thunderbird

Mod + Comma (,)
--   Ncmpcpp Music Player

Mod + Hyphen (-)
--   Transmission

Mod + Semicolon (;)
--   Ranger File Browser (urxvt)

Mod + Slash (/)
--   Ranger File Browser (st)

Mod + Backslash (\\)
--   Filezilla

Mod + N
--   Pulse Audio Control

Mod + Shift + Slash (/)
--   This Man Page Window

.SH SURF COMMANDS
Ctrl + H
--   Back

Ctrl + L
--   Forward

Ctrl + R
--   Refresh

Ctrl + G
--   Go to address

Ctrl + F
--   Find string on web page

Ctrl + N
--   Go to next search result

Ctrl + Shift + O
--   Open web inspector

Ctrl + B
--   Add current page to bookmarks

Ctrl + Shift + K
--   Zoom in

Ctrl + Shift + J
--   Zoom out

Ctrl + W
--   Play media on page in MPV

.SH SURF ADDRESS BAR PATTERNS

" [query]"
--   (Note the space) Search Duck Duck Go

"g [query]"
--   Search on Google

"gh [query]"
--   Search on GitHub

"w [query]"
--   Search on Wikipedia

"y [query]"
--   Search on YouTube

"v [query]"
--   Search on Void Linux wiki

"gf [query]"
--   Search on 4chan

.SH VIM COMMANDS
u
   - Undo

Ctrl + R
   - Redo

Ctrl + W
   - Jump to other window

dd
   - Delete the entire current line

d$
   - Delete the rest of the current line

dG
   - Deletes entire file

c
   - Cut text in Visual mode

y
   - Copy text in Visual mode

p
   - Paste text in Normal mode

:w
   - Write buffer to file, or with argument to write new file

:q
   - Quit after saving

:q!
   - Quit without saving

:wq
   - Save and quit

G
   - Jump to the bottom of the file

gg
   - Jump to the top of the file

?
   - Backwards search

/
   - Forwards search

.SH BSPWM SHORTCUTS
Mod + Shift + E
--   Exit BSPWM

Mod + Shift + R
--   Exit BSPWM

Mod + Shift + C
--   Close Window

Mod + T
--   Tiled Window State

Mod + S
--   Floating Window State

Mod + F
--   Fullscreen Window State

Mod + Shift + Q
--   Switch to Adjacent Window

Mod + O
--   Switch to Newer Window

Mod + I
--   Switch to Older Window

Mod + M
--   Monocle Layout

Mod + Arrow Keys
--   Move Floating Window
