.TH halp 1 "August 31, 2019" "BSPWM Key Bindings" "My Key Shortcuts"
.SH NAME
halp \- list of my user-defined key shortcuts
.SH PROGRAMS
Mod + Return
--   Terminal (st)

Mod + Shift + Return
--   Tabbed Terminal (st)

Mod + Space
--   Dmenu

Mod + Period (.)
--   Surf

Mod + Shift + Period (.)
--   Thunderbird

Mod + Comma (,)
--   Ncmpcpp Music Player

Mod + Hyphen (-)
--   Transmission

Mod + Semicolon (;)
--   Ranger File Browser (urxvt)

Mod + Slash (/)
--   Ranger File Browser (st)

Mod + Backslash (\\)
--   Filezilla

Mod + N
--   Pulse Audio Control

Mod + E
--   JGMenu App Launcher

Mod + Shift + Slash (/)
--   This Man Page Window

.SH SURF COMMANDS
Ctrl + Shift + Enter
--   Open new tab

Ctrl + H
--   Back

Ctrl + L
--   Forward

Ctrl + R
--   Refresh

Ctrl + G
--   Go to address

Ctrl + F
--   Find string on web page

Ctrl + N
--   Go to next search result

Ctrl + Shift + O
--   Open web inspector

Ctrl + B
--   Add current page to bookmarks

Ctrl + Shift + K
--   Zoom in

Ctrl + Shift + J
--   Zoom out

Ctrl + Shift + W
--   Move tab left

Ctrl + Shift + E
--   Move tab right

Ctrl + W
--   Play media on page in MPV

.SH SURF ADDRESS BAR PATTERNS

" [query]"
--   (Note the space) Search Duck Duck Go

"g [query]"
--   Search on Google

"gh [query]"
--   Search on GitHub

"w [query]"
--   Search on Wikipedia

"y [query]"
--   Search on YouTube

"v [query]"
--   Search on Void Linux wiki

.SH SHELL ALIASES

"a [file]"
--   'bat', Rust file viewer and concatenator

"b"
--   'neofetch', system information tool, with options

"c [directory]"
--   cds into the specified directory

"cat [file]"
--   'bat' in place of 'cat'

"conf [program]"
--   Edits the main configuration file for a certain program

"d"
--   cds into ~/Downloads

"df"
--   'df -h -T' in place of 'df'

"e"
--   'cargo build --release' - compiles Rust project

"f [image]"
--   Opens the image in Feh, image viewer

"g [command] [options]"
--   'git' with no arguments - add 'push', 'pull', etc.

"ga [file]"
--   'git add' - adds a file to staging area

"gc [commit or branch] -- [file]"
--   'git checkout' - checks out branch, commit, or file

"gcb [new branch name]"
--   Creates a new branch with name, switches to it

"gcm [commit message]"
--   Commits with the specified message

"gl"
--   'git log' - show last several commits in a pager

"gpush"
--   'git push origin master' - don't run if pushing to another branch

"gpull"
--   'git pull origin master'

"gr [file]"
--   'git remove' - removes file from staging area and deletes it

"grc [file]"
--   'git remote --cached' - removes from staging area without deleting

"gs"
--   'git status' - show staged and unstaged changes

"i"
--   cds into ~/Videos

"jcommit"
--   Commits with the date for a message, and pushes

"k"
--   'make', optionally with arguments

"kc"
--   'make clean'

"l [directory]"
--   'lsd', Rust file lister, with options

"ls [directory]"
--   'lsd' in place of 'ls'

"lsl"
--   'lsd -l', for long listing

"lsa"
--   'lsd -A', for almost all entries

"lsla"
--   'lsd -lA', for long listing of all entries

"lst"
--   'lsd --tree', for tree listing

"m [video file]"
--   Play specified video file in MPV

"n"
--   Opens ncmpcpp Music Player

"o"
--   cds into ~/Documents

"p"
--   cds into ~/Pictures

"r"
--   'ranger', command-line file browser

"s"
--   SSHs into my website

"spi"
--   SSHs into the Raspberry Pi

"t [torrent file]"
--   Start Transmission with specified file

"tr [arguments]"
--   'transmission-remote', with mandatory arguments

"u"
--   cds into ~/Music

"v [file]"
--   Opens the specified file in Vim

"x"
--   Starts a new zsh instance as root

"z [arguments]"
--   'tmux', optionally with arguments

.SH VIM COMMANDS
u
   - Undo

Ctrl + R
   - Redo

Ctrl + W
   - Jump to other window

dd
   - Delete the entire current line

d$
   - Delete the rest of the current line

dG
   - Deletes entire file

c
   - Cut text in Visual mode

y
   - Copy text in Visual mode

p
   - Paste text in Normal mode

:w
   - Write buffer to file, or with argument to write new file

:q
   - Quit after saving

:q!
   - Quit without saving

:wq
   - Save and quit

G
   - Jump to the bottom of the file

gg
   - Jump to the top of the file

?
   - Backwards search

/
   - Forwards search

.SH BSPWM SHORTCUTS
Mod + Shift + E
--   Exit BSPWM

Mod + Shift + R
--   Exit BSPWM

Mod + Shift + C
--   Close Window

Mod + T
--   Tiled Window State

Mod + S
--   Floating Window State

Mod + F
--   Fullscreen Window State

Mod + Shift + Q
--   Switch to Adjacent Window

Mod + O
--   Switch to Newer Window

Mod + I
--   Switch to Older Window

Mod + M
--   Monocle Layout

Mod + Arrow Keys
--   Move Floating Window
