######################################################################
# 
#  File        :  user.action
# 
#  Purpose     :  User-maintained actions file, see
#                 https://www.privoxy.org/user-manual/actions-file.html
#
######################################################################

# This is the place to add your personal exceptions and additions to
# the general policies as defined in default.action. (Here they will be
# safe from updates to default.action.) Later defined actions always
# take precedence, so anything defined here should have the last word.

# See https://www.privoxy.org/user-manual/actions-file.html, or the
# comments in default.action, for an explanation of what an "action" is
# and what each action does.

# The examples included here either use bogus sites, or have the actual
# rules commented out (with the '#' character). Useful aliases are
# included in the top section as a convenience.

#############################################################################
# Aliases
#############################################################################
{{alias}}
#############################################################################
#
# You can define a short form for a list of permissions - e.g., instead
# of "-crunch-incoming-cookies -crunch-outgoing-cookies -filter -fast-redirects",
# you can just write "shop". This is called an alias.
#
# Currently, an alias can contain any character except space, tab, '=', '{'
# or '}'.
# But please use only 'a'-'z', '0'-'9', '+', and '-'.
#
# Alias names are not case sensitive.
#
# Aliases beginning with '+' or '-' may be used for system action names 
# in future releases - so try to avoid alias names like this.  (e.g. 
# "+crunch-all-cookies" below is not a good name)
#
# Aliases must be defined before they are used.
# 
# These aliases just save typing later:
#
+crunch-all-cookies = +crunch-incoming-cookies +crunch-outgoing-cookies
-crunch-all-cookies = -crunch-incoming-cookies -crunch-outgoing-cookies
 allow-all-cookies  = -crunch-all-cookies -session-cookies-only -filter{content-cookies}
 allow-popups       = -filter{all-popups} -filter{unsolicited-popups}
+block-as-image     = +block{Blocked image request.} +handle-as-image
-block-as-image     = -block

# These aliases define combinations of actions
# that are useful for certain types of sites:
#
fragile     = -block -crunch-all-cookies -filter -fast-redirects -hide-referer -prevent-compression
shop        = -crunch-all-cookies allow-popups

# Your favourite blend of filters:
#
myfilters   = +filter{html-annoyances} +filter{js-annoyances} +filter{all-popups}\
              +filter{webbugs} +filter{banners-by-size}

# Allow ads for selected useful free sites:
#
allow-ads   = -block -filter{banners-by-size} -filter{banners-by-link}
#... etc.  Customize to your heart's content.

## end aliases ########################################################
#######################################################################

# Begin examples: #####################################################

# Say you have accounts on some sites that you visit regularly, and you
# don't want to have to log in manually each time. So you'd like to allow
# persistent cookies for these sites. The allow-all-cookies alias defined
# above does exactly that, i.e. it disables crunching of cookies in any
# direction, and the processing of cookies to make them only temporary.
#
{ allow-all-cookies }
#.sourceforge.net
#sunsolve.sun.com
#slashdot.org
#.yahoo.com
#.msdn.microsoft.com
#.redhat.com

# Say the site where you do your homebanking needs to open popup
# windows, but you have chosen to kill popups uncoditionally by default.
# This will allow it for your-example-bank.com:
#
{ -filter{all-popups} }
.banking.example.com

# Some hosts and some file types you may not want to filter for
# various reasons:
#
{ -filter }

# Technical documentation is likely to contain strings that might
# erroneously get altered by the JavaScript-oriented filters:
#
#.tldp.org
#/(.*/)?selfhtml/

# And this stupid host sends streaming video with a wrong MIME type,
# so that Privoxy thinks it is getting HTML and starts filtering:
#
stupid-server.example.com/


# Example of a simple "block" action. Say you've seen an ad on your
# favourite page on example.com that you want to get rid of. You have
# right-clicked the image, selected "copy image location" and pasted
# the URL below while removing the leading http://, into a { +block{reason} }
# section. Note that { +handle-as-image } need not be specified, since
# all URLs ending in .gif will be tagged as images by the general rules
# as set in default.action anyway:
#
{ +block{Nasty ads.} }
www.example.com/nasty-ads/sponsor.gif

# The URLs of dynamically generated banners, especially from large banner
# farms, often don't use the well-known image file name extensions, which
# makes it impossible for Privoxy to guess the file type just by looking
# at the URL. 
# You can use the +block-as-image alias defined above for these cases.
# Note that objects which match this rule but then turn out NOT to be an
# image are typically rendered as a "broken image" icon by the browser.
# Use cautiously.
#
{ +block-as-image }
#.doubleclick.net
#/Realmedia/ads/
#ar.atwola.com/

# Now you noticed that the default configuration breaks Forbes
# Magazine, but you were too lazy to find out which action is the
# culprit, and you were again too lazy to give feedback, so you just
# used the fragile alias on the site, and -- whoa! -- it worked. The
# 'fragile' aliases disables those actions that are most likely to break
# a site. Also, good for testing purposes to see if it is Privoxy that
# is causing the problem or not.
# 
{ fragile }
#.forbes.com

# Here are some sites we wish to support, and we will allow their ads
# through.
#
{ allow-ads }
#.sourceforge.net
#.slashdot.org
#.osdn.net

# user.action is generally the best place to define exceptions and
# additions to the default policies of default.action. Some actions are
# safe to have their default policies set here though. So let's set a
# default policy to have a 'blank' image as opposed to the checkerboard
# pattern for ALL sites. '/' of course matches all URLs.
# patterns:
#
{ +set-image-blocker{blank} }
#/

# Enable the following section (not the regression-test directives)
# to rewrite and redirect click-tracking URLs on news.google.com.
# Disabling JavaScript should work as well and probably works more reliably.
#
# Redirected URL = http://news.google.com/news/url?ct2=us%2F0_0_s_1_1_a&sa=t&usg=AFQjCNHJWPc7ffoSXPSqBRz55jDA0KgxOQ&cid=8797762374160&url=http%3A%2F%2Fonline.wsj.com%2Farticle%2FSB10001424052970204485304576640791304008536.html&ei=YcqeTsymCIjxggf8uQE&rt=HOMEPAGE&vm=STANDARD&bvm=section&did=-6537064229385238098
# Redirect Destination = http://online.wsj.com/article/SB10001424052970204485304576640791304008536.html
# Ignore = Yes
#
{+fast-redirects{check-decoded-url}}
news.google.com/news/url.*&url=http.*&

{+hide-user-agent{Asshole/1.0}}
/

{+block{Ad servers}}
adservice.google.*
.*advert*.
2468.go2cloud.org
.amarktflow.com
amarktflow.com
apps.id.net
.apps.id.net
data.cnn.com
apple.com-notice.info
*.apple.com-notice.info
dobre-programy.*
jackbootedroom.com
*.jackbootedroom.com
login.dotomi.*
cdn.googletoolservices.com
fgoogle.com
s.sh
is.sh
hosted.stats.com
hosted.stats.com.*
metrics.
mysterysnooper.com
*.mysterysnooper.com
quickcash-system.com
performanceadexchange.com
privacyassistant.net
gstatic.com
*.gstatic.com
apis.google.com
id.google.com
rereddit.com
*.rereddit.com
plus.google.com
0.beta.facebook.com
*.channel.facebook.com
*.tfbnw.net
beta.vvv.facebook.com
bidv.m.facebook.com
bg-bg.facebook.com
*.fbcdn.net
infowars.com
homeschooling.news
hoax.news
ironictimes.com
sheeple.news
shoebat.com
sgtreport.com
secondamendment.news
scientific.news
science.news
satanism.news
space.news
trafficking.com
treason.news
transhumanism.news
womenshealth.news
worldtruth.tv
s.zkcdn.net
stealthedeal.com
tags.news.com.au
twitter.com
*.twitter.com
twitter.cm
ttwitter.com
*.ttwitter.com
vdtrack.com
*.vdtrack.com
urldelivery.com
*.urldelivery.com
googletagmanager.com
*.googletagmanager.com
googletagservices.com
*.googletagservices.com
ping.chartbeat.net
stats.wp.com
aoredi.com
gamblerush.com
*.gamblerush.com
bidgear.com
*.bidgear.com
track.adtrue.com
pakistanelevators.pk
*.pakistanelevators.pk
cpm20.com
*.cpm20.com
media.complex.com
analysis.polarisoffice.com
analytics-digit-in.cdn.ampproject.org
analytics.jabong.com
analytics.logsss.com
analytics.mailmunch.co
analytics.picsart.com
*.analytics.picsart.com
analytics.poolshool.com
analytics.posttv.com
analytics.pokki.com
robux.dev
*.rtk.io
zarget.com
alog.umeng.com
alog.umengcloud.com
*.alphonso.tv
analytics.rayjump.com
client-analytics.braintreegateway.com
securemetrics.apple.com
smetrics.bestbuy.com
log.snapdeal.com
log.getdropbox.com
dev.appboy.com
api.cloudmobi.net
api.quantumgraph.com
manifest.localytics.com
*.startappservice.com
h-sdk.online-metrix.net
tracking.i2w.io
c.webengage.com
prebid.adnxs.com
*.zdbb.net
sstats.adobe.com
analytics.archive.org
analytics.bitrix.info
analytics.htmedia.in
analytics.myfinance.com
*.soperson.com
talk99.cn
*.talk99.cn
ampmetrics.engadget.com
c.adskeeper.co.uk
datacollect.vmall.com
event.ksosoft.com
events.appsflyer.com
track.tenjin.io
api.stats.appa.pe
api5.batmobil.net
applog.uc.cn
matchmyip.com
*.matchmyip.com
ads.aerserv.com
ads.mp.mydas.mobi
*.ads.mp.mydas.mobi
sdktm.w.inmobi.com
device-metrics-us.amazon.com
adsflame.com
adtekmedia.com
adv.axiatraders.com
ads.nexage.com
api.oneaudience.com
pixel.realclever.com
ads.feedly.com
metrics.adage.com
applog.camera360.com
*.applog.camera360.com
*.applovin.com
roboinside.me
*.roboinside.me
rotator.
analytics.
service.face2trade.com
sionicmedia.com
tracking.beginads.com
tradersbrokers.com
ads.proc.cc
15.taboola.com
*.15.taboola.com
*.taboola.com
cdn5.userzoom.com
web.vortex.data.microsoft.com
telecommand.telemetry.microsoft.com
watson.telemetry.microsoft.com
profile.localytics.com
manifest.localytics.com
cradver.livejasmin.com
*.aria.microsoft.com
*.data.microsoft.com
*.*.data.microsoft.com
*.miui.com
mywot.com
mywot.net
ads5.truecaller.com
ae.gsecondscreen.com
cdn-jp.gsecondscreen.com
unconf.adkmob.com
watson.telemetry.microsoft.com
graph.accountkit.com
ma312-r.analytics.edgesuite.net
wzrkt.com
*.bitmedianetwork.com
gum.criteo.com
in8.zog.link
trafforsrv.com
*.trafforsrv.com
cosiloon.com
kuikdelivery.com
pushedwebnews.com
newlimitedoffer.com
d-and-h.com
*.pushedwebnews.com
*.newlimitedoffer.com
app.storage.yunvm.com
*.app.storage.yunvm.com
pull-3045.kxcdn.com
tvpage.com
*.tvpage.com
ad.wynk.in
appcdn.tvpage.com
service.videoplaza.tv
adserver.adtech.de
app-measurement.com
beauty-tea.com
zekiatagur.com
arkonziv.com
*.beauty-tea.com
*.zekiatagur.com
*.arkonziv.com
tracking.
telemetry.
cws.conviva.com
*.cws.conviva.com
banner.org.ua
powerad.ai
powertradeprofit.com
beap-bc.yahoo.com
*.exoclick.com
*.ero-advertising.com
hrtya.com
*.hrtya.com
myfreecams.com
*.myfreecams.com
freeadult.games
*.livejasmin.com
amazonco.uk
ads.samsungads.com
grabify.link
bmwforum.co
stopify.co
spottyfly.com
xn--yotu-1ra.be
freegiftcards.co
quickmessage.us
iplogger.org
2no.co
*.iplogger.org
*.2no.co
iplogger.ru
*.iplogger.ru
com-fasting.live
*.com-fasting.live
joinmy.site
watches-my.stream
youshouldclick.us
yip.su
ladsup.com
powerad.ai
hotspot.cz
hobby-hangar.net
mlpoint.pt
mmile.com
mobatory.com
updo.nl
yougube.com
youtibe.com
youtuhe.com
yumekin.com
z32538.nb.host127-0-0-1.com
zkic.com
zous.szm.sk
paypai.org
sunonsunday.com
avast-downloads.com
blacksnake.com
google-docs.info
gooqleapi.com
*.adtimaserver.vn
admin.iad.eclick.vn
*.eclick.vn
*.admicro.vn
*.vcmedia.com
*.vcmedia.vn
adnetwork.vn
*.adnetwork.vn
novaonads.com
*.novaonads.com
novaon.asia
*.novaon.asia
*.lavanetwork.net
*.polyad.net
polyad.net
*.ants.vn
ad360.vn
*.ad360.vn
selfpwn.org
suckdude.com
thatsjustgay.com
turdgasm.com
vomitgirl.org
thehomo.org
themacuser.org
whipcrack.org
wormgush.com
auto.search.msn.com
media.fastclick.net
cdn.fastclick.net
www.google-analytics.l.google.com
ssl.google-analytics.com
ssl-connection.net
stat.livejournal.com
ads.imeem.com
0stats.com
*.cqcounter.com
006.free-counter.co.uk
006.freecounters.co.uk
abclnks.com
7zip.fr
4-counter.com
adclient.rottentomatoes.com
adblock.fr
adadvisor.net
analytics.msnbc.msn.com
analytics.myfinances.com
analytics.prx.org
a-nj.1rx.io
an.mlb.com
amateur.xxxcounter.com
apple.com-onlinesupport.host
app.yesware.com
a.predictvideo.com
a-ssl.ligatus.com
a.visualrevenue.com
best-search.cc
be.sitestat.com
beacon.
bserver.blick.com
bstats.adbrite.com
*.statcounter.com
click.icptrack.com
clickauditor.net
click.atdmt.com
cjt1.net
clickmeter.com
*.stats.esomniture.com
fastcounter.
freerapid.fr
foxcounter.com
googfle.com
goldstats.com
gostats.com
g-wizzads.net
hc2.humanclick.com
highscanprotect.com
js.cybermonitor.com
js.hs-analytics.net
jdownloader.fr
kqzyfj.com
leadpub.com
linkcounter.com
linkcounter.pornosite.com
link.masterstats.com
ostats.mozilla.com
stats.
s.youtube.com
tags.bkrtx.com
tag.crsspxl.com
tipsurf.com
themecounter.com
ourtoolbar.com
omtrdc.net
okcounter.com
o.addthis.com
*.sitemeter.com
scrooge.nbc11.com
scrooge.nbc4.com
scrooge.click10.com
sclk.org
s.clickability.com
sa.jumptap.com
*.opentracker.net
tracker.
tracking.
trackmail3345.com
*.spylog.com
*.*.spylog.com
tynt.com
t.yesware.com
udc.msn.com
uk.cqcounter.com
uip.semasio.net
valueclick.com
valueclick.net
video-stats.video.google.com
vip.clickzs.com
v7.stats.load.com
usa.nedstat.net
us.2.cqcounter.com
ultimatecounter.com
webcounter.
webtrends.
*.web-stat.com
sitestat.com
simpletrck.com
*.sitestat.com
sostats.mozilla.com
spklds.com
s.stats.wordpress.com
stat1.z-stat.com
stast2.gq.com
ss.tiscali.it
ss.tiscali.com
ntp.msn.com
0byv9mgbn0.com
30-day-change.com
*.30-day-change.com
*.360.cn
44chan.me
88chan.pw
*.360safe.com
*.adcolony.com
unconf.adkmob.com
sdk.adincube.com
facebooktoday.cc
googlephoto.vip
mcsoft365.com
antivirus-covid19.site
instaboom-hello.site
*.jave.xyz
covid19-info.online
amerisleep.github.io
chicksaddlery.net
track-js.link
labbe.biz
energycoffe.org
adorebeauty.org
map-js.link
zapaljs.com
link-js.link
teacoffe.net
abtasty.net
slickjs.org
ukcoffe.com
top5value.com
info-js.link
mechat.info
jewsondirect.com
closetlondon.org
ottocap.org
auth-mail.email
mail-auth.email
accountsgoog1e.com
dokertest.xyz
testdom1.xyz
navyfederai.org
mynavyfedral.org
an.facebook.com
pixel.facebook.com
*.ezmob.com
*.eyereturn.com
api.factual.com
geopulse.factual.com
intake.factual.com
fam-ad.com
img.fam-ad.com
fancrew.jp
*.featureforward.com
facebook.com
www.facebook.com
facebook.be
facebook.it
facebook.fr
facebook.jp
facebook.se
facebook.us
facebook.cm
instagram.com
logger.instagram.com
platform.instagram.com
www.instagram.com
facebookcrawl.co.cc
facebook-proxy.hi5.com
facebookunblocking.com
fastdownload10.com
fastnclick.com
ezthemes.com
eyes.by
fabrics-store.com
marketingplatform.google.com
adservice.google.co.in
bacr.com.pk
googlew.com
googlre.com
googlwe.com
goolegames.com
goolges.com
gopeds.com
gopogle.com
gratisweb.com
grabfile.co
gulf-industrial.com
*.younetmedia.com
*.adpia.vn
*.cityads.com
cityadstrack.com
*.adsota.com
*.adsplay.net
*.adsplay.xyz
adsplay.net
adsplay.xyz
*.adsparc.com
sporttv.today
*.sporttv.today
*.vidoomy.com
*.adflex.vn
akibaol.com
stagolk.com
rsa.pub
bot2.googlerenewals.net
init.sh
init.ps
ap-ms.net
artizaa.com
myamystills.com
freeoldsafe.com
renovatesystem.com
yhdpbn.fr
yhdsite.com
yhdyhd.ro
fjrncj.org
sitejfn.ch
servmain.info
mainpbn.org

# Enable the following section (not the regression-test directives)
# to block various Facebook "like" and similar tracking URLs.  At the
# time this section was added it was reported to not break Facebook
# itself but this may have changed by the time you read this. This URL
# list is probably incomplete and if you don't have an account anyway,
# you may prefer to block the whole domain.
#
# Blocked URL = http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Ffacebook.com%2Farstechnica&width=300&colorscheme=light&show_faces=false&stream=false&header=false&height=62&border_color=%23FFFFFF
# Ignore = Yes
# Blocked URL = http://www.facebook.com/plugins/activity.php?site=arstechnica.com&width=300&height=370&header=false&colorscheme=light&recommendations=false&border_color=%23FFFFFF
# Ignore = Yes
# Blocked URL = http://www.facebook.com/plugins/fan.php?api_key=368513495882&connections=10&height=250&id=8304333127&locale=en_US&sdk=joey&stream=false&width=377
# Ignore = Yes
# Blocked URL = http://www.facebook.com/plugins/like.php?api_key=368513495882&channel_url=http%3A%2F%2Fstatic.ak.fbcdn.net%2Fconnect%2Fxd_proxy.php%3Fversion%3D3%23cb%3Df13997452c%26origin%3Dhttp%253A%252F%252Fonline.wsj.com%252Ff1b037e354%26relation%3Dparent.parent%26transport%3Dpostmessage&extended_social_context=false&href=http%3A%2F%2Fonline.wsj.com%2Farticle%2FSB10001424052970204485304576640791304008536.html&layout=button_count&locale=en_US&node_type=link&ref=wsj_share_FB&sdk=joey&send=false&show_faces=false&width=90
# Ignore = Yes
#
{+block{Facebook "like" and similar tracking URLs.}}
www.facebook.com/(extern|plugins)/(login_status|like(box)?|activity|fan)\.php

{+block{Google fuckhead niggers}}
#.google.com

