#!/bin/sh

SXHKD_FIFO=/tmp/sxhkd-fifo
export SXHKD_FIFO

[ -e "$SXHKD_FIFO" ] && rm "$SXHKD_FIFO"
mkfifo "$SXHKD_FIFO"
sxhkd -s "$SXHKD_FIFO" -c ~/.config/sxhkd/sxhkdrc &

feh --bg-scale ~/.config/bspwm/wallpaper.jpg &

bspc monitor -d I II III IV V VI VII

bspc config focused_border_color	\#128230
bspc config active_border_color		\#812017
bspc config normal_border_color		\#020402
bspc config focus_follows_pointer	true
bspc config border_width			1
bspc config window_gap				8
bspc config focus_follows_pointer	true
bspc config initial_polarity		first_child
bspc config center_pseudo_tiled		true
bspc config single_monocle			true

bspc config split_ratio				0.5
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc rule -a Gimp desktop='^5' state=floating
bspc rule -a ranger desktop='^5' state=monocle focus=on follow=on
bspc rule -a feh state=floating follow=on focus=on
bspc rule -a 'Firefox Developer Edition' desktop='^2' state=tiled
bspc rule -a 'Firefox Developer Edition':Dialog desktop='^2' state=floating
bspc rule -a 'Firefox Developer Edition':Browser desktop='^2' state=tiled
bspc rule -a 'Sublime Text 3' desktop='^4' state=tiled
bspc rule -a 'Sublime' desktop='^4' state=tiled
bspc rule -a Thunderbird desktop='^6' state=tiled
bspc rule -a mpv desktop='^3' state=floating focus=on follow=on
bspc rule -a *:Dialog state=floating
bspc rule -a Firefox:Dialog desktop='^2' state=floating
bspc rule -a Firefox:Places desktop='^2' state=floating
bspc rule -a Firefox:Browser desktop='^2' state=tiled
bspc rule -a Firefox:Toplevel desktop='^2' state=tiled
bspc rule -a Firefox-esr:Dialog desktop='^2' state=floating
bspc rule -a Firefox-esr:Places desktop='^2' state=floating
bspc rule -a Firefox-esr:Browser desktop='^2' state=tiled
bspc rule -a Firefox-esr:Toplevel desktop='^2' state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#xbindkeys
xinput --set-prop 14 'libinput Accel Speed' 0.55
xinput --set-prop 14 'libinput Tapping Enabled' 1
xmodmap -e 'keycode 80=Up'
xmodmap -e 'keycode 88=Down'
xmodmap -e 'keycode 83=Left'
xmodmap -e 'keycode 85=Right'

killall polybar
polybar -r -log=error bspbar &
killall compton
compton -b --opengl --blur-background --blur-kern 5x5box --sw-opti &
xrandr --output eDP-1 --brightness 0.7
