#!/bin/sh

xsetroot -cursor_name left_ptr
xrdb -merge .Xresources

SXHKD_FIFO=/tmp/sxhkd.fifo
export SXHKD_FIFO

[ -e "$SXHKD_FIFO" ] && rm "$SXHKD_FIFO"
mkfifo "$SXHKD_FIFO"
sxhkd -s "$SXHKD_FIFO" -c ~/.config/sxhkd/sxhkdrc &

bspc monitor -d I II III IV V VI

bspc config focused_border_color    \#949894
bspc config active_border_color	    \#202020
bspc config normal_border_color	    \#020402
bspc config focus_follows_pointer   true
bspc config border_width            1
bspc config window_gap              4
bspc config focus_follows_pointer   true
bspc config initial_polarity        first_child
bspc config center_pseudo_tiled     true
bspc config single_monocle          true

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a Gimp desktop='^5' state=floating
bspc rule -a feh state=floating follow=on focus=on
bspc rule -a Firefox desktop='^2' state=tiled
bspc rule -a 'Mozilla Firefox' desktop='^2' state=tiled
bspc rule -a vlc desktop='^3' state=floating focus=on follow=on
bspc rule -a surf desktop='^2' state=tiled
bspc rule -a tabbed-surf desktop='^2' state=tiled
bspc rule -a surf2 desktop='^2' state=tiled
bspc rule -a Surf desktop='^2' state=tiled
bspc rule -a 'Sublime Text 3' desktop='^4' state=tiled
bspc rule -a 'Sublime' desktop='^4' state=tiled
bspc rule -a Thunderbird desktop='^6' state=tiled
bspc rule -a mpv desktop='^3' state=floating focus=on follow=on
bspc rule -a *:Dialog state=floating
bspc rule -a Firefox:Dialog desktop='^2' state=floating
bspc rule -a Firefox:Places desktop='^2' state=floating
bspc rule -a Firefox:Browser desktop='^2' state=tiled
bspc rule -a Firefox:Toplevel desktop='^2' state=tiled
bspc rule -a Firefox-esr:Dialog desktop='^2' state=floating
bspc rule -a Firefox-esr:Places desktop='^2' state=floating
bspc rule -a Firefox-esr:Browser desktop='^2' state=tiled
bspc rule -a Firefox-esr:Toplevel desktop='^2' state=tiled
bspc rule -a Screenkey manage=off

#xbindkeys
xinput --set-prop 18 'Synaptics Tap Action' 1, 1, 1, 1, 1, 1, 1
xinput --set-prop 18 'Synaptics Tap Time' 120
xmodmap -e 'keycode 80=Up'
xmodmap -e 'keycode 88=Down'
xmodmap -e 'keycode 83=Left'
xmodmap -e 'keycode 85=Right'

killall polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar -r -log=error bspbar &

killall compton

while pgrep -u $UID -x compton >/dev/null; do sleep 1; done

compton -c --shadow-exclude 'class_g = "Polybar" || class_g = "Firefox" || class_g = "surf" || class_g = "Thunderbird"' &

xrandr --output eDP1 --brightness 0.6

