#!/bin/sh

SXHKD_FIFO=/tmp/sxhkd-fifo
export SXHKD_FIFO

[ -e "$SXHKD_FIFO" ] && rm "$SXHKD_FIFO"
mkfifo "$SXHKD_FIFO"

[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
pgrep -x panel > /dev/null || panel &

sxhkd -s "$SXHKD_FIFO" -c ~/.config/sxhkd/sxhkdrc &

feh --bg-scale ~/.config/bspwm/wallpaper.jpg &

bspc monitor -d I II III IV V VI

bspc config focused_border_color	\#E28728
bspc config normal_border_color		\#808080
bspc config single_monocle		true
bspc config initial_polarity		first_child
bspc config focus_follows_pointer	true
bspc config border_width         	2
bspc config window_gap          	12

bspc config split_ratio          	0.5
bspc config borderless_monocle		true
bspc config gapless_monocle      	true
bspc config center_pseudo_tiled		true

bspc rule -a feh focus=on state=floating
bspc rule -a Chromium focus=on desktop=^2 state=tiled
bspc rule -a Gedit focus=on follow=on desktop=^4
bspc rule -a vlc focus=on follow=on desktop=^3
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

killall compton
compton &
