#+TITLE: Foot
#+AUTHOR: Tanner Babcock
#+EMAIL: babkock@protonmail.com
#+STARTUP: showeverything
#+OPTIONS: toc:nil num:nil
#+DESCRIPTION: Foot terminal config on Tanner Babcock GitHub Pages. Features colors, fonts, and preferences.
#+KEYWORDS: tanner babcock, tanner, babcock, emacs, github, foot, doom emacs, org mode, linux, gnu linux, void linux, art, experimental, noise
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+HTML_HEAD_EXTRA: <meta property="og:image" content="/images/ogimage.png" />
#+HTML_HEAD_EXTRA: <meta property="og:image:width" content="660" />
#+HTML_HEAD_EXTRA: <meta property="og:image:height" content="461" />
#+HTML_HEAD_EXTRA: <meta property="og:title" content="Foot" />
#+HTML_HEAD_EXTRA: <meta property="og:description" content="Foot terminal config on Tanner Babcock GitHub Pages. Features colors, fonts, and preferences." />
#+HTML_HEAD_EXTRA: <meta property="og:locale" content="en_US" />
#+HTML_HEAD_EXTRA: <link rel="icon" href="/images/favicon.png" />
#+HTML_HEAD_EXTRA: <link rel="apple-touch-icon" href="/images/apple-touch-icon-180x180.png" />
#+HTML_HEAD_EXTRA: <link rel="icon" href="/images/icon-hires.png" sizes="192x192" />
#+PROPERTY: header-args:ini :tangle
#+LANGUAGE: en

This is the configuration for the [[https://codeberg.org/dnkl/foot][Foot]] terminal. This literate configuration is available on my [[https://babkock.github.io/configs/foot.html][GitHub Pages]]. Please, if you appreciate my work, please consider [[https://www.paypal.com/donate/?business=X8ZY4CNBJEXVE&no_recurring=0&item_name=Please+help+me+pay+my+bills%2C+and+make+more+interesting+GNU%2FLinux+content%21+I+appreciate+you%21&currency_code=USD][making a donation]].

#+BEGIN_EXPORT html
<header>
    <center>
        <ul>
            <li><a href="https://babkock.github.io">Home</a></li>
            <li><a href="https://tannerbabcock.com/home" target="_blank">Website</a></li>
            <li><a href="https://github.com/Babkock" target="_blank">GitHub</a></li>
            <li><a href="https://github.com/Babkock/Babkock.github.io" target="_blank">Source Code</a></li>
            <li><a href="https://gitlab.com/Babkock/" target="_blank">GitLab</a></li>
            <li><a href="https://www.youtube.com/user/Babk0ck" target="_blank">YouTube</a></li>
        </ul>
    </center>
</header>
#+END_EXPORT

# #+TOC: headlines 2

* Table of Contents :toc:
- [[#sway][Sway]]
  - [[#font][Font]]
  - [[#preferences][Preferences]]
  - [[#appearance][Appearance]]
  - [[#colors][Colors]]
- [[#wayfire][Wayfire]]
  - [[#font-1][Font]]
  - [[#preferences-1][Preferences]]
  - [[#appearance-1][Appearance]]
  - [[#colors-1][Colors]]
- [[#hyprland][Hyprland]]
  - [[#font-2][Font]]
  - [[#preferences-2][Preferences]]
  - [[#appearance-2][Appearance]]
  - [[#colors-2][Colors]]
- [[#niri][Niri]]
  - [[#font-3][Font]]
  - [[#preferences-3][Preferences]]
  - [[#appearance-3][Appearance]]
  - [[#colors-3][Colors]]

* Sway

** Font

#+begin_src conf :tangle sway.ini
shell = /usr/bin/zsh

font = SpaceMono Nerd Font:pixelsize=19:antialias=true
font-bold = SpaceMono Nerd Font:style=Bold:pixelsize=19:antialias=true
font-italic = SpaceMono Nerd Font:style=Italic:pixelsize=19:antialias=true
font-bold-italic = SpaceMono Nerd Font:style=Bold Italic:pixelsize=19:antialias=true
#+end_src

** Preferences

#+begin_src conf :tangle sway.ini
dpi-aware=yes
pad=9x9 center
vertical-letter-offset=-4px
notify=notify-send -i ${app-id} {$title} {$body}
line-height=24px
letter-spacing=-1px
bold-text-in-bright=palette-based
resize-delay-ms=90
#+end_src

** Appearance

#+begin_src conf :tangle sway.ini
[cursor]
style=beam
blink=yes

[bell]
urgent=yes
notify=yes
visual=yes

[mouse]
hide-when-typing=yes
alternate-scroll-mode=no

[url]
launch=xdg-open ${url}

[colors]
background=020202
foreground=eeeeee
alpha=0.6
flash=ffffff
#+end_src

** Colors

#+begin_src conf :tangle sway.ini
regular0=000000
bright0=121212
regular1=ee0009
bright1=fe0219
regular2=99cf01
bright2=a9df11
regular3=e4cf13
bright3=f4df23
regular4=6b65da
bright4=6264fe
regular5=af38db
bright5=ff4de7
regular6=43e7e9
bright6=53f7f9
regular7=eecd73
bright7=fedd83
urls=ff0000
#+end_src

* Wayfire

** Font

#+begin_src conf :tangle wayfire.ini
shell = /usr/bin/zsh

font = SpaceMono Nerd Font:pixelsize=19:antialias=true
font-bold = SpaceMono Nerd Font:style=Bold:pixelsize=19:antialias=true
font-italic = SpaceMono Nerd Font:style=Italic:pixelsize=19:antialias=true
font-bold-italic = SpaceMono Nerd Font:style=Bold Italic:pixelsize=19:antialias=true
#+end_src

** Preferences

#+begin_src conf :tangle wayfire.ini
dpi-aware=yes
pad=9x9 center
vertical-letter-offset=-4px
line-height=24px
letter-spacing=-1px
bold-text-in-bright=palette-based
resize-delay-ms=90
#+end_src

** Appearance

#+begin_src conf :tangle wayfire.ini
[cursor]
style=beam
blink=yes

[colors]
background=101010
foreground=efefef
alpha=0.6
#+end_src

** Colors

#+begin_src conf :tangle wayfire.ini
regular0=000000
bright0=121212
regular1=c77188
bright1=d78198
regular2=00bb10
bright2=00cc20
regular3=dfdf10
bright3=efef20
regular4=2995db
bright4=39a5eb
regular5=b97e76
bright5=c98e86
regular6=489390
bright6=58a4a1
regular7=edc9b9
bright7=fdd9c9
#+end_src

* Hyprland

** Font

#+begin_src conf :tangle hyprland.ini
shell = /usr/bin/zsh

font = SpaceMono Nerd Font:pixelsize=19:antialias=true
font-bold = SpaceMono Nerd Font:style=Bold:pixelsize=19:antialias=true
font-italic = SpaceMono Nerd Font:style=Italic:pixelsize=19:antialias=true
font-bold-italic = SpaceMono Nerd Font:style=Bold Italic:pixelsize=19:antialias=true
#+end_src

** Preferences

#+begin_src conf :tangle hyprland.ini
dpi-aware=yes
pad=9x9 center
notify=notify-send -i ${app-id} ${title} ${body}
vertical-letter-offset=-4px
line-height=24px
letter-spacing=-1px
bold-text-in-bright=palette-based
resize-delay-ms=80
#+end_src

** Appearance

#+begin_src conf :tangle hyprland.ini
[cursor]
style=beam
blink=yes

[bell]
urgent=yes
notify=yes
visual=yes

[url]
launch=xdg-open ${url}

[colors]
background=100002
foreground=fdeadb
alpha=0.6
#+end_src

** Colors

This is where you edit the actual color scheme.

#+begin_src conf :tangle hyprland.ini
regular0=000000
bright0=121212
regular1=c03b3e
bright1=d04b4e
regular2=15b082
bright2=25c192
regular3=e27725
bright3=f28735
regular4=3996c0
bright4=49a6d0
regular5=e73d7b
bright5=f74e8b
regular6=c8988a
bright6=d8a89a
regular7=eddacb
bright7=fdeadb
#+end_src

* Niri

** Font

#+begin_src conf :tangle niri.ini
shell = /usr/bin/zsh

font = SpaceMono Nerd Font:pixelsize=19:antialias=true
font-bold = SpaceMono Nerd Font:style=Bold:pixelsize=19:antialias=true
font-italic = SpaceMono Nerd Font:style=Italic:pixelsize=19:antialias=true
font-bold-italic = SpaceMono Nerd Font:style=Bold Italic:pixelsize=19:antialias=true
#+end_src

** Preferences

#+begin_src conf :tangle niri.ini
dpi-aware=yes
pad=9x9 center
vertical-letter-offset=-4px
notify=notify-send -i ${app-id} {$title} {$body}
line-height=24px
letter-spacing=-1px
bold-text-in-bright=palette-based
resize-delay-ms=90
#+end_src

** Appearance

#+begin_src conf :tangle niri.ini
[cursor]
style=beam
blink=yes

[bell]
urgent=yes
notify=yes
visual=yes

[mouse]
hide-when-typing=yes
alternate-scroll-mode=no

[url]
launch=xdg-open ${url}

[colors]
background=020202
foreground=eeeeee
alpha=0.5
flash=ffffff
#+end_src

** Colors

#+begin_src conf :tangle niri.ini
regular0=000000
bright0=121212
regular1=e04a00
bright1=ff2800
regular2=81c071
bright2=93eab9
regular3=e3af67
bright3=fdcb46
regular4=4bc8dc
bright4=6be8fc
regular5=e56f95
bright5=f36c97
regular6=0fbd98
bright6=12e5b8
regular7=dddddd
bright7=ffffff
urls=ff0000
#+end_src

#+BEGIN_EXPORT html
<footer>
    <center>
    <p>Copyright &copy; 2026 Tanner Babcock.</p>
    <p><a href="https://babkock.github.io">Home</a> &nbsp;&bull;&nbsp;
    <a href="https://github.com/Babkock/Babkock.github.io" target="_blank">Source Code</a> &nbsp;&bull;&nbsp;
    <a href="https://tannerbabcock.com/home">Website</a> &nbsp;&bull;&nbsp;
    <a href="https://gitlab.com/Babkock/Dotfiles">Dotfiles</a> &nbsp;&bull;&nbsp;
    <a href="https://www.twitch.tv/babkock">Twitch</a> &nbsp;&bull;&nbsp;
    <a href="https://www.paypal.com/donate/?business=X8ZY4CNBJEXVE&no_recurring=0&item_name=Please+help+me+pay+my+bills%2C+and+make+more+interesting+GNU%2FLinux+content%21+I+appreciate+you%21&currency_code=USD"><i>Donate!</i></a></p>
    </center>
</footer>
#+END_EXPORT
