#+TITLE: Foot
#+AUTHOR: Tanner Babcock
#+EMAIL: babkock@protonmail.com
#+STARTUP: showeverything
#+OPTIONS: toc:nil num:nil
#+DESCRIPTION: Foot terminal config on Tanner Babcock GitHub Pages. Features colors, fonts, and preferences.
#+KEYWORDS: tanner babcock, tanner, babcock, emacs, github, foot, doom emacs, org mode, linux, gnu linux, void linux, art, experimental, noise
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+HTML_HEAD_EXTRA: <meta property="og:image" content="/images/ogimage.png" />
#+HTML_HEAD_EXTRA: <meta property="og:image:width" content="660" />
#+HTML_HEAD_EXTRA: <meta property="og:image:height" content="461" />
#+HTML_HEAD_EXTRA: <meta property="og:title" content="Foot" />
#+HTML_HEAD_EXTRA: <meta property="og:description" content="Foot terminal config on Tanner Babcock GitHub Pages. Features colors, fonts, and preferences." />
#+HTML_HEAD_EXTRA: <meta property="og:locale" content="en_US" />
#+HTML_HEAD_EXTRA: <link rel="icon" href="/images/favicon.png" />
#+HTML_HEAD_EXTRA: <link rel="apple-touch-icon" href="/images/apple-touch-icon-180x180.png" />
#+HTML_HEAD_EXTRA: <link rel="icon" href="/images/icon-hires.png" sizes="192x192" />
#+PROPERTY: header-args:ini :tangle
#+LANGUAGE: en

This is the configuration for the [[https://codeberg.org/dnkl/foot][Foot]] terminal. This literate configuration is available on my [[https://babkock.github.io/configs/foot.html][GitHub Pages]]. Please, if you appreciate my work, please consider [[https://www.paypal.com/donate/?business=X8ZY4CNBJEXVE&no_recurring=0&item_name=Please+help+me+pay+my+bills%2C+and+make+more+interesting+GNU%2FLinux+content%21+I+appreciate+you%21&currency_code=USD][making a donation]].

#+BEGIN_EXPORT html
<header>
    <center>
        <ul>
            <li><a href="https://babkock.github.io">Home</a></li>
            <li><a href="https://tannerbabcock.com/home" target="_blank">Website</a></li>
            <li><a href="https://github.com/Babkock" target="_blank">GitHub</a></li>
            <li><a href="https://github.com/Babkock/Babkock.github.io" target="_blank">Source Code</a></li>
            <li><a href="https://gitlab.com/Babkock/" target="_blank">GitLab</a></li>
            <li><a href="https://www.youtube.com/user/Babk0ck" target="_blank">YouTube</a></li>
        </ul>
    </center>
</header>
#+END_EXPORT

# #+TOC: headlines 2

* Table of Contents :toc:
- [[#hyprland][Hyprland]]
  - [[#font][Font]]
  - [[#preferences][Preferences]]
  - [[#appearance][Appearance]]
  - [[#colors][Colors]]
- [[#sway][Sway]]
  - [[#font-1][Font]]
  - [[#preferences-1][Preferences]]
  - [[#appearance-1][Appearance]]
  - [[#colors-1][Colors]]
- [[#labwc][LabWC]]
  - [[#font-2][Font]]
  - [[#preferences-2][Preferences]]
  - [[#appearance-2][Appearance]]
  - [[#colors-2][Colors]]

* Hyprland

** Font

#+begin_src conf :tangle foot.ini
font = SpaceMono Nerd Font:pixelsize=19:antialias=true
font-bold = SpaceMono Nerd Font:style=Bold:pixelsize=19:antialias=true
font-italic = SpaceMono Nerd Font:style=Italic:pixelsize=19:antialias=true
font-bold-italic = SpaceMono Nerd Font:style=Bold Italic:pixelsize=19:antialias=true
#+end_src

** Preferences

#+begin_src conf :tangle foot.ini
dpi-aware=yes
pad=9x9 center
vertical-letter-offset=-4px
line-height=25px
letter-spacing=-1px
bold-text-in-bright=palette-based
resize-delay-ms=80
#+end_src

** Appearance

#+begin_src conf :tangle foot.ini
[cursor]
style=beam
blink=yes

[colors]
background=100002
foreground=fdeadb
alpha=0.6
#+end_src

** Colors

This is where you edit the actual color scheme.

#+begin_src conf :tangle foot.ini
regular0=000000
bright0=121212
regular1=c03b3e
bright1=d04b4e
regular2=15b082
bright2=25c192
regular3=e27725
bright3=f28735
regular4=3996c0
bright4=49a6d0
regular5=e73d7b
bright5=f74e8b
regular6=c8988a
bright6=d8a89a
regular7=eddacb
bright7=fdeadb
#+end_src

* Sway

** Font

#+begin_src conf :tangle sway.ini
font = SpaceMono Nerd Font:pixelsize=19:antialias=true
font-bold = SpaceMono Nerd Font:style=Bold:pixelsize=19:antialias=true
font-italic = SpaceMono Nerd Font:style=Italic:pixelsize=19:antialias=true
font-bold-italic = SpaceMono Nerd Font:style=Bold Italic:pixelsize=19:antialias=true
#+end_src

** Preferences

#+begin_src conf :tangle sway.ini
dpi-aware=yes
pad=9x9 center
vertical-letter-offset=-4px
line-height=25px
letter-spacing=-1px
bold-text-in-bright=palette-based
resize-delay-ms=90
#+end_src

** Appearance

#+begin_src conf :tangle sway.ini
[cursor]
style=beam
blink=yes

[colors]
background=030303
foreground=eeeeee
alpha=0.6
#+end_src

** Colors

#+begin_src conf :tangle sway.ini
regular0=000000
bright0=121212
regular1=b93b2b
bright1=d54044
regular2=40a789
bright2=50b799
regular3=dedc91
bright3=eeeca1
regular4=61b8a6
bright4=71c9b7
regular5=b06998
bright5=c26cd5
regular6=6d878d
bright6=42717b
regular7=eeeeee
bright7=fefefe
#+end_src

* LabWC

** Font

#+begin_src conf :tangle labwc.ini
font = SpaceMono Nerd Font:pixelsize=19:antialias=true
font-bold = SpaceMono Nerd Font:style=Bold:pixelsize=19:antialias=true
font-italic = SpaceMono Nerd Font:style=Italic:pixelsize=19:antialias=true
font-bold-italic = SpaceMono Nerd Font:style=Bold Italic:pixelsize=19:antialias=true
#+end_src

** Preferences

#+begin_src conf :tangle labwc.ini
dpi-aware=yes
pad=9x9 center
vertical-letter-offset=-4px
line-height=25px
letter-spacing=-1px
bold-text-in-bright=palette-based
resize-delay-ms=90
#+end_src

** Appearance

#+begin_src conf :tangle labwc.ini
[cursor]
style=beam
blink=yes

[colors]
background=101010
foreground=efefef
alpha=0.6
#+end_src

** Colors

#+begin_src conf :tangle labwc.ini
regular0=000000
bright0=121212
regular1=c77188
bright1=d78198
regular2=00bb10
bright2=00cc20
regular3=dfdf10
bright3=efef20
regular4=2995db
bright4=39a5eb
regular5=b97e76
bright5=c98e86
regular6=489390
bright6=58a4a1
regular7=edc9b9
bright7=fdd9c9
#+end_src

#+BEGIN_EXPORT html
<footer>
    <center>
    <p>Copyright &copy; 2022 Tanner Babcock.</p>
    <p><a href="https://babkock.github.io">Home</a> &nbsp;&bull;&nbsp;
    <a href="https://github.com/Babkock/Babkock.github.io" target="_blank">Source Code</a> &nbsp;&bull;&nbsp;
    <a href="https://tannerbabcock.com/home">Website</a> &nbsp;&bull;&nbsp;
    <a href="https://gitlab.com/Babkock/Dotfiles">Dotfiles</a> &nbsp;&bull;&nbsp;
    <a href="https://www.twitch.tv/babkock">Twitch</a> &nbsp;&bull;&nbsp;
    <a href="https://www.paypal.com/donate/?business=X8ZY4CNBJEXVE&no_recurring=0&item_name=Please+help+me+pay+my+bills%2C+and+make+more+interesting+GNU%2FLinux+content%21+I+appreciate+you%21&currency_code=USD"><i>Donate!</i></a></p>
    </center>
</footer>
#+END_EXPORT
